## #############################################
#  APLICAÇÃO
## #############################################
spring.application.name=microservico-radares-appia
info.app.version=1.0.0

# 1. Define o perfil de produção como ativo
spring.profiles.active=dev
#spring.profiles.active=prod

# A aplicação tentará buscar o config server, se falhar (optional:),
# ela continuará e usará o 'application-prod.properties' local como fallback.
spring.config.import=optional:configserver:http://config-server:8888

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

spring.jackson.serialization.write-dates-as-timestamps=false