## #############################################
#  HTTP
## #############################################
server.port=8092

## #############################################
#  RABBITMQ E MENSAGERIA NATIVA
## #############################################
# Custom properties lidas pela classe RabbitMQConfig e RadarMqPublisher
rabbitmq.exchange.name=radares_exchange
rabbitmq.routing.key=radares.appia

# Reconexao (Spring AMQP / RabbitTemplate)
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=5000ms

## #############################################
#  CACHE (Redis)
## #############################################
spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

## #############################################
#  OPENAPI / SWAGGER UI
## #############################################
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=API Radares Concession\u00E1ria APPIA
springdoc.info.version=1.0.0
springdoc.info.description=Microsservi\u00E7o de leituras de radares \u2014 Concession\u00E1ria APPIA

## #############################################
#  HEALTH CHECK E METRICAS (Actuator / Prometheus)
## #############################################
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

## #############################################
#  LOGGING E BANNER
## #############################################
spring.main.banner-mode=console
logging.level.com.inteligencia=DEBUG

## #############################################
#  EUREKA
## #############################################
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}



